
if GetLocale() ~= "esES" then return end
local _, sm = ...
local L = sm.L
L["1. Background"] = "Fondo" -- Needs review
L["2. Border"] = "Borde" -- Needs review
L["3. Artwork"] = "Artwork" -- Needs review
L["Addon Buttons"] = "Botones del Addon" -- Needs review
L["Alpha Key (1-bit alpha)"] = "Alpha Key (1-bit alpha)" -- Needs review
L["Always"] = "Siempre" -- Needs review
L["Armored Man"] = "Hombre Armado" -- Needs review
L["Background Color"] = "Color del Fondo" -- Needs review
L["Background Texture"] = "Textura del Fondo" -- Needs review
L["Border Color"] = "Color del Borde" -- Needs review
L["Borders"] = "Bordes" -- Needs review
L["Border Texture"] = "Textura del Borde" -- Needs review
L["Buttons"] = "Botones" -- Needs review
L["Calendar"] = "Calendario" -- Needs review
L["Circle"] = "Círculo" -- Needs review
L["Copy a Profile"] = "Copiar un Perfil" -- Needs review
L["Delete a Profile"] = "Borrar un Perfil" -- Needs review
L["Dungeon Difficulty Indicator (When Available)"] = "Indicador de Dificultad de Mazmorra (Cuando esté disponible)" -- Needs review
L["Enable"] = "Habilitar" -- Needs review
L["Enable Coordinates"] = "Habilitar Coordenadas" -- Needs review
L["Font Size"] = "Tamaño de Fuente" -- Needs review
L["Height"] = "Alto" -- Needs review
L["Hexagon"] = "Hexágono" -- Needs review
L["Horizontal Position"] = "Posición Horizontal" -- Needs review
L["HUD Color"] = "Color HUD" -- Needs review
L["Map Button"] = "Botón del Mapa" -- Needs review
L["Name"] = "Nombre" -- Needs review
L["Never"] = "Nunca" -- Needs review
L["Octagon"] = "Octógono" -- Needs review
L["Really delete this profile?"] = "¿De verdad quieres borrar este perfil?" -- Needs review
L["Right Click Configure"] = "Configurar Click Derecho" -- Needs review
L["Right clicking the map will open the SexyMap options"] = "Haciendo click derecho en el mapa se abrirán las opciones de SexyMap" -- Needs review
L["Rotation Speed (seconds)"] = "Velocidad de Rotación (segundos)" -- Needs review
L["Route 66"] = "Ruta 66" -- Needs review
L["Save current settings as preset..."] = "Guardar configuración actual como predeterminada..." -- Needs review
L["Scale"] = "Escala" -- Needs review
L["Spice up your minimap with some sexy options."] = "Condimenta tu minimapa con unas cuantas opciones sexys." -- Needs review
L["Text Color"] = "Color del Texto" -- Needs review
L["Texture"] = "Textura" -- Needs review
L["Texture Options"] = "Opciones de Textura" -- Needs review
L["The time it takes (in seconds) to complete one rotation. A setting of 0 turns off rotation."] = "El tiempo que tardará (en segundos) en dar una vuelta completa. Marcar 0 deshabilitará la rotación" -- Needs review
L["Visibility"] = "Visibilidad" -- Needs review
L["Width"] = "Ancho" -- Needs review
L["Zoom In Button"] = "Botón de Acercar Zoom" -- Needs review
L["Zoom Out Button"] = "Botón de Alejar Zoom" -- Needs review


